### PR TITLE
DOCS-15980 ubuntu compatibility

### PR DESCRIPTION
**Pull request by davemungo**
## DESCRIPTION

STAGING
[mongodump](https://docs-mongodbcom-staging.corp.mongodb.com/database-tools/docsworker-xlarge/DOCS-15980-ubuntu-compatibility/mongodump/#additional-considerations)
[mongorestore](https://docs-mongodbcom-staging.corp.mongodb.com/database-tools/docsworker-xlarge/DOCS-15980-ubuntu-compatibility/mongorestore/#additional-considerations)

[JIRA](https://jira.mongodb.org/browse/DOCS-15980)
[Tools] mongodump/mongorestore compatibility issue w/ Ubuntu 18.0.4

[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=642dbe92b49106a498a74089)

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Is this free of spelling errors?
- [ ] Is this free of grammatical errors?
- [ ] Is this free of staging / rendering issues?
- [ ] Are all the links working?

## External Review Requirements

[What's expected of an external reviewer?](https://wiki.corp.mongodb.com/display/DE/Reviewing+Guidelines+for+the+MongoDB+Server+Documentation)

### CODE REVIEW

**Review by jeff-allen-mongo — COMMENTED** [review]
@davemungo thanks for this update. Left a few suggestions.

Jeff

**Review by davemungo — COMMENTED** [review]
Thank for the feedback @jeff-allen-mongo  

This is ready for another look

**Review by jeff-allen-mongo — APPROVED** [review]
LGTM

**Comment by davemungo** [comment]
From slack:

Will Huang 
[12:04](https://mongodb.slack.com/archives/D0527MG87L4/p1680797070845239)
Hey Dave, I saw the staging doc for both mongorestore and mongodump. It :lgtm:

[12:04](https://mongodb.slack.com/archives/D0527MG87L4/p1680797097081679)
I don't havbe permission to approve it so just letting you know here.

**Pull request merged**
